<?php

namespace app\common\controller;

use app\common\model\AuthRule;
use think\auth\Auth;
use think\Controller;

class AdminBase extends Controller
{
    //
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        if(!session('admin_user')){
            $this->redirect('login/index');
        }

//        $this->checkAuth();
        $this->getMenu();
    }


    /**
     * 检查权限
     */
    public function checkAuth()
    {

        $module = $this->request->module();
        $controller = $this->request->controller();
        $action = $this->request->action();

        //排除
        $not_check = ['admin/Index/index','admin/System/clear','admin/AuthGroup/getjson'];



//        dump($module.'/'.$controller.'/'.$action);
//        dump(in_array($module.'/'.$controller.'/'.$action,$not_check));exit;

        if(!in_array($module.'/'.$controller.'/'.$action,$not_check)){

            $admin_id = session('admin_user')['id'];
            $auth = new Auth();

            if(!$auth->check($module.'/'.$controller.'/'.$action,$admin_id)){
                $this->error('没有权限！');
            }

        }

    }


    /**
     * 获取侧边栏菜单
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    public function getMenu()
    {
        $menu = [];
        $admin_id = session('admin_user')['id'];
        $auth_rule_list = db('auth_rule')->where('status',1)->order(['sort'=>'desc','id'=>'asc'])->select();
        $auth = new Auth();

        foreach ($auth_rule_list as $v){
            if( $auth->check($v['name'],$admin_id) || ($admin_id==1) ){
                $menu[]=$v;
            }
        }

        $menu = empty($menu) ? [] : array2tree($menu);

        $this->assign(compact('menu'));
    }

}
